### ISSUE TITLE
node 0.12.x support

### ISSUE THREAD

**Issue by geddski** [docpad/docpad#984]
I can't install this on node 0.12.4, get this error:

```sh
npm ERR! Darwin 14.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.4
npm ERR! npm  v2.10.1
npm ERR! code ELIFECYCLE

npm ERR! js2coffee@0.2.7 preinstall: `npm run-script ./cyclic.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the js2coffee@0.2.7 preinstall script 'npm run-script ./cyclic.js'.
npm ERR! This is most likely a problem with the js2coffee package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run-script ./cyclic.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls js2coffee
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/dave/domo/domoweb/DomoWeb/npm-debug.log
dave@geddskimac-2 ~/d/d/DomoWeb> docpad update
error: null
error: null
TypeError: undefined is not a function
    at Object.exports.eval (/usr/local/lib/node_modules/docpad/node_modules/cson/node_modules/coffee-script/lib/coffee-script/coffee-script.js:120:47)
    at Object.CSON.parseSync (/usr/local/lib/node_modules/docpad/node_modules/cson/out/lib/cson.js:109:32)
    at null._onTimeout (/usr/local/lib/node_modules/docpad/node_modules/cson/out/lib/cson.js:89:22)
    at Timer.listOnTimeout (timers.js:110:15)
```

**Comment by cletusw** [comment]
@geddski Are you installing the latest version of docpad? I get this error when trying to install docpad < 6.65.0, but 6.65.0 and above work fine on node 0.12.0, npm 2.5.1.

It looks like in docpad 6.65.0 the cson dependency was updated to 1.6.0 which updated the js2coffee dependency to 0.3.5 which works with npm 2.

**Comment by balupton** [comment]
Try `docpad update --global` to ensure the update is being performed via the global docpad install, as perhaps the local docpad install can't update itself
