### ISSUE TITLE
Error after update to 6.47

### ISSUE THREAD

**Issue by todojs** [docpad/docpad#581]
After npm update I recive this error when try run docpad:

error: Something went wrong with the action
error: An error occured:
Error: Cannot find module 'extendr'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
