### ISSUE TITLE
Heroku Woes with Docpad 6.59.6

### ISSUE THREAD

**Issue by stelabouras** [docpad/docpad#750]
I have just upgraded my project to Docpad 6.59.6 and it works perfectly on my local configuration (Node 0.10.24, Npm 1.3.21) but I get the following error every time I push my repo to Heroku (which currently supports up to Node 0.10.21 & Npm 1.3.11):

```
2013-12-30T17:13:39.156645+00:00 heroku[web.1]: Starting process with command `node_modules/docpad/bin/docpad-server`
2013-12-30T17:13:40.081837+00:00 app[web.1]: 
2013-12-30T17:13:40.082005+00:00 app[web.1]: module.js:340
2013-12-30T17:13:40.082221+00:00 app[web.1]:     throw err;
2013-12-30T17:13:40.082221+00:00 app[web.1]:           ^
2013-12-30T17:13:40.086121+00:00 app[web.1]: Error: Cannot find module 'ignorefs'
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Function.Module._resolveFilename (module.js:338:15)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Function.Module._load (module.js:280:25)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Module.require (module.js:364:17)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at require (module.js:380:17)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/docpad/out/lib/docpad.js:64:14)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/docpad/out/lib/docpad.js:4311:4)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2013-12-30T17:13:40.086121+00:00 app[web.1]:     at Module.load (module.js:356:32)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Module.require (module.js:364:17)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at require (module.js:380:17)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/docpad/out/bin/docpad-server.js:5:12)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/docpad/out/bin/docpad-server.js:48:4)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Module.load (module.js:356:32)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2013-12-30T17:13:40.086316+00:00 app[web.1]:     at Module.require (module.js:364:17)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at require (module.js:380:17)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/docpad/bin/docpad-server:2:1)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at Module._compile (module.js:456:26)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at Object.Module._extensions..js (module.js:474:10)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at Module.load (module.js:356:32)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at Function.Module._load (module.js:312:12)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at Function.Module.runMain (module.js:497:10)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at startup (node.js:119:16)
2013-12-30T17:13:40.086478+00:00 app[web.1]:     at node.js:901:3
```

Upon further investigation I found two solutions:

a) When I change Docpad version to 6.53.4 (my previous one) on my package.json file, everything works perfectly for Heroku after the git push
b) If I maintain the latest Docpad version (6.59.6) and copy paste Docpad's dependencies to my own package.json, everything is resolved as well.

So it seems like a dependency issue to me. Do I have a messed up Heroku configuration on my part, or is it part of a bigger Docpad issue? :(

**Comment by balupton** [comment]
Closing in favour of https://github.com/docpad/docpad/issues/1081
