### ISSUE TITLE
Cannot create Docpad instance when migrating from Docpad 6.82.5 to 6.83.2

### ISSUE THREAD

**Issue by apesteguy** [docpad/docpad#1141]
Hello,

I am running into this error when trying to instanciate Docpad:

```
info: Create Docpad instance
error: Cannot create docpad object TypeError: envFile.parseFile is not a function
    at Task.<anonymous> (C:\Source\Git\website\node_modules\docpad\edition-esnext\lib\docpad.js:1784:24)
    at ambi (C:\Source\Git\website\node_modules\ambi\source\index.js:77:3)
    at Domain.fireMethod (C:\Source\Git\website\node_modules\taskgroup\source\task.js:542:5)
    at Domain.run (domain.js:370:15)
    at Task.fire (C:\Source\Git\website\node_modules\taskgroup\source\task.js:560:15)
    at Immediate.<anonymous> (C:\Source\Git\website\node_modules\taskgroup\source\task.js:595:20)
    at processImmediate (internal/timers.js:461:21)
    at process.topLevelDomainCallback (domain.js:144:15)
    at process.callbackTrampoline (internal/async_hooks.js:129:14)
```
    

It seems that the `parseFile` function does not exist in the `envfile@^6.14.0` dependent modules.

How to fix this issue?

Best Regards!

**Comment by balupton** [comment]
Seems an incompatibility with one of the dep APIs that weren't picked up by the tests, so an upgrade of the dep was done and caused an issue with usage. Can you share the results with the `--debug` flag.

I can't release any fixes yet, as still wrestling with moving over our build infrastructure from Travis CI to GitHub Actions, which has been a hickup since November.

If you'd like this to become a priority once the build infrastructure is ready, [then please sponsor](https://github.com/sponsors/balupton), otherwise I have other issues that I need to focus my limited unpaid time on.
